### ISSUE TITLE
Cancel APIActionCreators

### ISSUE THREAD

**Issue by AlanFoster** [addthis/fluxthis#104]
Is it possible to cancel APIActionCreator requests?

Scenario - 

As a user types input a search field we trigger an API Action Creator.
As this XHR is waiting for a response, the user types another letter, and another XHR request occurrs

There is a potential race condition here, as the first request may be received after the second request and return the wrong results to the user.

Is it possible to cancel this first API call?

**Comment by jhorwit2** [comment]
we actually had some talks to allow optimistic canceling of requests based on same paths. For example, if we request route A and while that request is executing the same exact request comes then keep then either 1) Keep first and ignore second or 2) cancel first and submit second. 

As of right now we do not have a way to cancel requests. I'll keep this ticket open and investigate it or if you want to submit a PR that would probably be quicker :).

**Comment by jhorwit2** [comment]
one quick idea i have without really look into the code would be to return a wrapper object when you call the API Action Creator that abstracts canceling the xhr request.

**Comment by AlanFoster** [comment]
I would love for fluxthis to handle the optimistic cancelling of requests. But I feel like that's too specific of a use case for fluxthis to deal with. In particular i'd be worried about the various edge cases which would need to be considered too.

What would your thoughts on triggering an event if you explicitly want to cancel a specific or all outgoing requests? This would require state within the APIActionCreators though, which i'm unsure about.

**Comment by jhorwit2** [comment]
So, here is my thinking.

```
export default React.createClass({
   onClick() {
       if (this.state.request.isPending()) {
            // Or maybe do a this.state.request.cancel();
            return;
       }
       const request = SomeAPIActionCreator.doRequest();
       this.setState({request});
   }
   render() {
     // some stuff
   }
})
``` I'm kinda thinking the application itself should handle the state of the requests since canceling requests is a pretty specific use case. Thoughts?

**Comment by jhorwit2** [comment]
After some poking around the code, this would be super easy. I'm going to pass it around internally to get some opinions if anyone has a better way to handle this. Let me know what you think also.

**Comment by AlanFoster** [comment]
:+1: To letting the application deal with the cancelling of requests. I definitely think it would be beneficial to return a useful object from the APIActionCreator for the purposes of cancelling requests

**Comment by jhorwit2** [comment]
#106
