### ISSUE TITLE
checkImmutable

### ISSUE THREAD

**Issue by matrinox** [addthis/fluxthis#105]
This is what it looks like:
```es6
static checkImmutable(item) {
	return item instanceof Immutable.Iterable || !(item instanceof Object);
}
```
This code `item instanceof Immutable.Iterable` works only if the item was created by same Immutable instance. If you import Immutable from a different source, say FB's immutable, `checkImmutable` will return false despite it being the same 'class' of Immutable! Using `Immutable.Iterable.isIterable(item)` will return true regardless of what Immutable instance was used to create the item. I suggest using that instead of what is currently in use.

**Comment by jhorwit2** [comment]
Our library uses facebook's immutable library, which is why we have that check. Is there an issue you ran into? Perhaps your version does not match ours? This is something we should probably move to a peer dependency.

**Comment by jhorwit2** [comment]
After doing a little more research your way is more safe. #108

**Comment by jmrog** [comment]
I'm inclined to think that it's worth making the change @matrinox suggested. Even using the same version of Immutable.js won't resolve some thorny issues. -- d'oh, you just updated with your comment. :P

**Comment by matrinox** [comment]
:+1:
