### ISSUE TITLE
Leave body untouched during an error parsing

### ISSUE THREAD

**Issue by AlanFoster** [addthis/fluxthis#115]
This issue is a followup on #112

If we now trigger error events as part of a JSON parsing failure as part of #112, we should most likely leave the body as it is. Currently there is no way to access this information without reaching into `err.message`

#### Current Implementation

https://github.com/engenb/fluxthis/blob/2a32eb393e478b5a6750f656a1f7b4a01a0c79dc/lib/implore.es6.js#L98

```js
try {
  response.body = JSON.parse(responseText);
} catch (err) {
  err.message = err.message + ' while parsing `' +
          responseText + '`';
  response.body = {};
  response.status = xhr.status || 0;
  response.error = err;
}
```

#### Potential Implementation

```js
try {
  response.body = JSON.parse(responseText);
} catch (err) {
  response.body = responseText;
  response.status = xhr.status || 0;
  response.error = err;
}
```

Thoughts?

**Comment by mako-taco** [comment]
How about this to avoid breaking backwards compatibility?

```
response.responseText = xhr.responseText;
response.status = xhr.status;
response.type = xhr.getResponseHeader('Content-Type');
```

**Comment by AlanFoster** [comment]
@mako-taco Apologies, I meant for `response.body = responseText` to still be there. Original post updated.

With regards to backwards compatibility; Personally I envision #112 to be a major release, and that this change would be perfect to go with it.

**Comment by mako-taco** [comment]
Good point.  horwitz and I are pretty busy at work right now if you wouldn't mind doing the PR.  We will publish to NPM and update the release notes afterwards.

**Comment by AlanFoster** [comment]
@mako-taco Will do; Happy to review #116 ? :+1:
