### ISSUE TITLE
Proposal: ImmutableReducerStore

### ISSUE THREAD

**Issue by AlanFoster** [addthis/fluxthis#133]
What are your thoughts on adding an additional Store to the fluxthis API which is in essence a ReducerStore. 

For instance, consider Facebook's [ReducerStore](https://github.com/facebook/flux/tree/b8fd975218245ff6ed72defa9e881ac03853b7ed#flux-utils) as a simple ReducerStore example. 

However with the power of fluxthis' API, we can do better than a single reducer function and a switch statement.

I therefore think an API such as the following would be cool - 

```js
var myStore = new ImmutableReducerStore({
    init: function () {
        this.defaultState = Immutable.fromJS({ 
            names: {}
        });

        // Map action methods to private methods.
        this.bindActions(
            'SET_NAME_VALUE', this.setNameValue
        );
    },

    public: {
        // Public methods remain the same and have access to `this.state`
    },

    private: {
        // Update private, Immutable values
        setNameValue: function (state, { id, name }) {
            return state.update('names', names => names.set(id, name));
        }
    }
});
```

Would love to hear your thoughts on this

**Comment by jhorwit2** [comment]
Ill chat with @makotaco. We actually have a huge rewrite in progress taking advantage of a lot of goodies. Pretty sure he had already something in mind like this.

**Comment by AlanFoster** [comment]
@jhorwit2 Mind sharing some of the high-level goals that are planned? It'd be great to see if there's any contributions we could help with :+1:

**Comment by jhorwit2** [comment]
Yea ill try to get a ticket setup next week with what we have been discussing.

**Comment by AlanFoster** [comment]
@jhorwit2 That'd be great, thanks! We've learnt a lot from using fluxthis for the past while, and would love to contribute / see what's in store

**Comment by jhorwit2** [comment]
:+1: I'll keep this ticket open for the time being.

**Comment by mako-taco** [comment]
@AlanFoster check out the work-in-progress [here](/addthis/fluxthis/tree/fluxthis-3.0)

**Comment by AlanFoster** [comment]
@mako-taco there's some cool API changes there :+1:
Out of interest, why the decision to nuke ApiAction creators?

**Comment by jhorwit2** [comment]
We plan to still have them. @AlanFoster. 

I'll probably start on them soon. I'm not sure how familiar you are with [dropwizard](https://dropwizard.github.io/dropwizard/0.6.2/manual/core.html#resources) but I have some plans to do annoations similar to that on es6 classes instead of config objects.

**Comment by mako-taco** [comment]
I really did not like ApiActionCreator.  I thought it was a ton of configuration, and a decent source of confusion. With the new  API, it should be very few lines of code to get the same effect:

```js
class CoolApiAction extends Action {
  act(cool) {
    $.post(`/cool/${cool}`)
      .success(res => this.enact(CoolApiSuccessAction, res))
      .fail(err => this.enact(CoolApiFailureAction, err));
  }
}
```

I didn't feel like the confusion it caused people / how much reading it took to learn made it worth it, but everyone tells me I'm wrong... and it seems like @jhorwit2 might implement them anyway.

**Comment by jhorwit2** [comment]
As @mako-taco said, there was perhaps some features we added that made it a little over the top. We will most likely slim down some of the features keeping only what we deem necessary. For example, we haven't really found a good use case of handleSuccess and handleFailure that couldn't be solved otherwise, so that will probably go.

**Comment by jhorwit2** [comment]
If you have an ideas @AlanFoster let us know.

**Comment by AlanFoster** [comment]
I would definitely be keen to keep API Action Creators as part of fluthis. It's nice to have a consistent API when calling RESTful services, and letting the JSON serializing/parsing be handled for us.

We currently use `handleFailure` in our application to check if the status code is a 401 unauthorised response. We then dispatch an additional event for this scenario for our application to deal with. Is this approach bad?

**Comment by mako-taco** [comment]
APIActionCreator will automatically dispatch the `failure` action passed to it, if one was provided, on failed requests (by default, any status code outsode of 200-300 range)
https://fluxthis.io/#/docs/api-action-creators

**Comment by AlanFoster** [comment]
@mako-taco That's true; The problem is we have a lot of API Action Creators. Having a Login store know about every single possible API Action Creator Failure is too much overhead, so firing a single expired login event seemed nicer.

I've put a PR up for this ImmutableReducerStore ticket now though - https://github.com/addthis/fluxthis/pull/141

Would appreciate a review! :)

**Comment by AlanFoster** [comment]
@mako-taco / @jhorwit2 Anything holding this back from being released? :+1:

**Comment by jhorwit2** [comment]
As far as I know we should be good. I'll chat with mako tomorrow. Company acquisition and stuff has made for a lot of side things to do. sorry about the slowness.

**Comment by jhorwit2** [comment]
@AlanFoster sorry about the delay (we have been traveling for work). v2.7.0 has been released.

**Comment by AlanFoster** [comment]
@jhorwit2 Awesome, thanks!
