### ISSUE TITLE
Allow named parameters with file formats

### ISSUE THREAD

**Issue by AlanFoster** [addthis/fluxthis#142]
Fluxthis does not currently support using named params in conjunction with a file format -

```js
  getMyModel: {
    route: '/my_models/:id.json'
    method: 'GET', 
    success: Actions.GET_MY_MODEL_SUCCESS,
    createRequest(id) {
      return {
        params: {
          id
        }
      };
    }
  }
```

When calling `getMyModel(1)` I would expect it to ping against `/my_models/1.json` instead it currently pings against `/my_models/:id.json` and 404s

Is this expected behaviour, or should it be changed within fluxthis?

**Comment by jhorwit2** [comment]
This is not expected. Do you mind submitting a PR?

**Comment by AlanFoster** [comment]
@jhorwit2 thanks for the confirmation :+1:
I wouldnt be in a position to add a PR for this currently though

**Comment by jmrog** [comment]
I can probably look into this some today.
