### ISSUE TITLE
Add the ability to mock store public methods for testing

### ISSUE THREAD

**Issue by jhorwit2** [addthis/fluxthis#15]
We should add the ability to mock public methods and be able to reset them when `Store.TestUtils.reset()` gets called. 

My thought process was we would expose a method with a prototype of:

`Store.TestUtils.mockMethod('methodName', newFunction)`

Then, whenever the store gets called, we would first check to see if the map of mocked objects contain that name, if so, use that function instead of the public member function.

**Comment by jhorwit2** [comment]
Actually the map approach won't work I don't think.

Perhaps we would:

1. Get the public member value for a given string
2. Store it 
3. Overwrite it with mocked function
4. Reset it back on reset()
5. profit

we would just need to add this functionality to the ObjectOrientedStore under TestUtils. The object containing all the goodies for public methods is `publicMethods`

**Comment by mako-taco** [comment]
This is for testing views, yes? How about
```js
Store.TestUtils.mockValues(() => {
  this.privateValue = 5;
  this.otherPrivateValue = Immutable.List([ ... ]);
});
```

**Comment by jhorwit2** [comment]
What about if you want to mock publics also? Im assuming you can do that there also?

On Sun, Mar 22, 2015 at 3:07 AM, addthis/fluxthis <reply@reply.github.com> wrote:

This is for testing views, yes? How about

Store.TestUtils.mockValues(() => {
  this.privateValue = 5;
  this.otherPrivateValue = Immutable.List([ ... ]);
});

-

**Comment by jhorwit2** [comment]
Not to self, replying via email sucks

**Comment by jhorwit2** [comment]
How would this work?
```

// Store calls mockValues
Store.TestUtils.mockValues(() => {
  this.privateValue = 5;
  this.otherPrivateValue = Immutable.List([ ... ]);
});

// Internal Store Code
function mockValues(callback) {
    for (var key in callback) {
       if (callback.hasOwnProperty(key)) {
          // store current `this` from store in an object and store new one temporarily
       }
    }
}
```

**Comment by mako-taco** [comment]
How about this then?  more like what you had before, but makes it easier to do it a bunch.
```js
Store.TestUtils.mockPublicMethods({
  methodName () {...},
  otherMethod () {...}
});
```
