### ISSUE TITLE
null thrown during jasmine testing

### ISSUE THREAD

**Issue by benkn** [addthis/fluxthis#16]
When testing my ActionCreator, I'm getting this error message sporadically:
```
TypeError: 'null' is not an object (evaluating 'err.message.match(RE_WARNING_EXPECTED)[1]')
```

From line 151 in ActionCreator, `validatePayload` method:
```
expected = err.message.match(RE_WARNING_EXPECTED)[1];
```

I'm not always setting a payloadType in my public methods.

**Comment by benkn** [comment]
Further investigation, using this payloadType caused the failure:
```
        //define what payloads for this action should look like
        payloadType: ActionCreator.PayloadTypes.shape({
            payload: ActionCreator.PayloadTypes.object,
            key: ActionCreator.PayloadTypes.string.isRequired,
            value: ActionCreator.PayloadTypes.string.isRequired
        }).isRequired,
```

**Comment by jhorwit2** [comment]
When you called the action when it produced the error did you see anything weird in the object? Like it didn't match what it was supposed to according to your payloadType above?

**Comment by mako-taco** [comment]
Any chance you could provide the payload that generates the error?

**Comment by jhorwit2** [comment]
I was able to reproduce.

```javascript
var ActionCreator = require('./src/ActionCreator.es6');

var ac = new ActionCreator({
    displayName: 'test',
    actionSource: 'test',
    doThing: {
        actionType: 'TEST',
        payloadType: ActionCreator.PayloadTypes.shape({
            payload: ActionCreator.PayloadTypes.object,
            key: ActionCreator.PayloadTypes.string.isRequired,
            value: ActionCreator.PayloadTypes.string.isRequired
        }).isRequired,
        createPayload(obj) {
            return {
                key: obj.test,
                value: obj.foo,
                payload: obj.payload
            };
        }
    }
});

ac.doThing({test: 'foo'});
```

Error:

``
`/Users/horwitz/programming/github/fluxthis/src/ActionCreator.es6.js:181 expected = err.message.match(RE_WARNING_EXPECTED)[1];
                                                    ^
TypeError: Cannot read property '1' of null
    at ActionCreator.validatePayload (/Users/horwitz/programming/github/fluxthis/src/ActionCreator.es6.js:181:53)
    at ActionCreator.<anonymous> (/Users/horwitz/programming/github/fluxthis/src/ActionCreator.es6.js:146:10)
    at Object.<anonymous> (/Users/horwitz/programming/github/fluxthis/test.js:23:4)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/lib/babel/api/register/node.js:102:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/lib/babel/api/register/node.js:115:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/bin/_babel-node:94:12)
horwitz@va-office-60 ~/p/g/fluxthis> 
```

**Comment by jhorwit2** [comment]
@benkn - the issue was when you did not pass a value in `createPayload` that is required in your `payloadType`
