### ISSUE TITLE
Use built bundle for tests instead of absolute paths to individual files

### ISSUE THREAD

**Issue by jhorwit2** [addthis/fluxthis#20]
the reason for this is so we ensure we arent breaking our builds. Our tests dont do us any good if thats the case.

The only exception should be files not exposed directly by requiring fluxthis.

**Comment by mako-taco** [comment]
how about a single test which tests the giant blob of `FluxThis` for specific properties?

**Comment by jhorwit2** [comment]
Imo its better to test the bundle file and just as easy as your way. Either way works in the end though.
