### ISSUE TITLE
allow stores to register themselves with arbitrary dispatchers

### ISSUE THREAD

**Issue by mako-taco** [addthis/fluxthis#4]
One step towards isomorphic support.

1. The default dispatcher instance must be used by default
2. A dispatcher can be passed to a store's constructor to associate it with that dispatcher
```js
let dispatcher = new ImmutableDispatcher();
new Store({dispatcher});
```

**Comment by jhorwit2** [comment]
We will want to move `var _lastID = 1;` in the dispatcher file into the dispatcher class itself as a symbol variable so multiple dispatchers don't share the same last id.
