### ISSUE TITLE
Optimize Implore Requests

### ISSUE THREAD

**Issue by jhorwit2** [addthis/fluxthis#52]
We should add two optimization efforts within implore. We should allow the ability to prevent duplicate route calls when the first once is still not finished. 

For example, lets say we request route A with `/path/id` then before the requests finishes we make the same request. We should ignore the second request since it's duplicate. 

We should also add an option to do the opposite. If we get the same request before the first one finishes, we should close the first one and open the second one.

**Comment by jhorwit2** [comment]
With this approach, we need to store the callbacks and execute each callback for a given request IF they are not the same. This means side effects in functions can be weird, so a note will need to be made of the behavior.

**Comment by jhorwit2** [comment]
Also, we should only make this optimization for GET requests, since closing requests on a PUT or POST or DELETE can have super weird side effects.

**Comment by mako-taco** [comment]
Since implore is promises now, I don't know if we can actually debounce the callbacks based on equality, since we are never handed them.  We can still debounce the network calls, though.

**Comment by jhorwit2** [comment]
Should we go back to normal callbacks?

**Comment by mako-taco** [comment]
I'm going to try an approach where we extend `Promise` and see where that takes me.  I'm also thinking of moving the success tests to implore so we can properly reject/resolve the promises

**Comment by jhorwit2** [comment]
Closing for now. We can reopen later.
