### ISSUE TITLE
Aaaaaahhhh! Typos.

### ISSUE THREAD

**Issue by Wildhoney** [addthis/fluxthis#55]
Reading: https://fluxthis.io/#/docs/dispatcher

> `var Dispatcher = require('fluxthis/src/distpatcherInstance.es6');`

Distpatcher? And then...

> And that's it! You can start using our **disptacher** to get super sick debugging.

![Cover Eyes](https://s-media-cache-ak0.pinimg.com/originals/ec/67/e2/ec67e2dc9285d30e918a08f1a6fcda92.jpg)

**Comment by jhorwit2** [comment]
![image](https://cloud.githubusercontent.com/assets/3876739/7262499/21a1b566-e848-11e4-944d-d180847d980d.png)

**Comment by jhorwit2** [comment]
Thanks for the ticket! Fixed it.

https://fluxthis.io/#/docs/dispatcher
`var Dispatcher = require('fluxthis/src/dispatcherInstance.es6');`

**Comment by Wildhoney** [comment]
Aaaaaand...

> And that's it! You can start using our **disptacher** to get super sick debugging. :+1:

**Comment by jhorwit2** [comment]
:+1:

**Comment by jhorwit2** [comment]
Fixed. Thanks :).

**Comment by jhorwit2** [comment]
Just a note, all our docs are at http://github.com/addthis/fluxthis.io

The docs themselves are all markdown.

Feel free to submit any PR's! We would love to accept them. :)

**Comment by Wildhoney** [comment]
Thanks! :+1: Will do if I spot any more.
