### ISSUE TITLE
add information on how to handle routing

### ISSUE THREAD

**Issue by santihbc** [addthis/fluxthis#56]
It would be great to document how routing is handled in AddThis. Routing is a topic where there is disagreement in the Flux community so setting a FluxThis way of doing it would round up a great documentation.

I suggest having the router be a Store that only silently updates the browser URL when listening to specific actions but does fire an action itself on first load to inform what is the entry point URL (that is the only time a Store can fire an Action directly)

**Comment by mako-taco** [comment]
we're working on a router to use with fluxthis... not quite ready for prime time, though. Probably would be a good idea to at least offer an example until a more codified way is done, though.

**Comment by jhorwit2** [comment]
@santihbc as mako said, we actually have been working on this internally because we came to the same realization as the community when it comes to the routers available. 

To answer your question, we use backbone's router in our dashboard on addthis.com; however, it has had some pain points. Another internal project tried routie. 

Our goal is to soon migrate away from these different routing libraries in favor of a flux router that integrates nicely with FluxThis to take advantage of debugging, testing, etc. 

Stay tuned!

**Comment by santihbc** [comment]
I will definitely be :). I was working in something like FluxThis and I came to the same exact conclusions as you did for every component of the Flux architecture but your implementation is better ;).

The router I was working with is based on "request" and has the characteristics I described. Are you in favor of a component syntax like the one currently offered in react-router or more of the silent store concept I mentioned before?

**Comment by mako-taco** [comment]
I've battled this out in my head a lot. My main goals for the router:
- provide a middleware based stack similar to Koa's which would allow for creation of actions in response to route changes
- provide a way to manage browser history (redirect, replace, etc)

In addition, there is the small matter of how the router affects the view. This is probably where most people disagree about what to do. I'll probably lean towards an optional mixin, but allow anyone who wants to use the store itself to update the view to do so.

**Comment by jhorwit2** [comment]
Mixins can invoke dispatches, thus updating the store. Given you aren't trying to invoke dispatches during life cycle methods where a previous dispatch is still executing.

I'm curious to see your koa like idea. Generators aren't yet prime time enough for browsers (they don't compile to es5 nicely). 

I have an idea that stems from how react-router handles things, except we fluxify it.

**Comment by jhorwit2** [comment]
Also, something to let your mind chew on:

We need to make sure our idea supports code splitting easily.

**Comment by mako-taco** [comment]
Here's koa routing w/ code splits
```js
Router({
	// show a loading gif when changing routes if we are making requets
	*'*' (next) {

		// setReactClass is a private method of the router store,
		// calling it will update views
		this.setReactClass(LoadingSpinner);
		yield next();	
	},

	// Start loading the settings component ASAP. Yield it since we don't
	// want to do any rendering until we have it
	*'/settings/*' (next) {
		let ctx = this;
		
		yield next();
		
		yield new Promise(resolve => {
			require.ensure(['Settings'], () => {
				let Settings = require('Settings');
				ctx.setReactClass(Settings);
				resolve();
			});
		});
	},

	// replaces a users history and url with one that contains their ID
	*'/settings/user' () {
		this.rewrite(`/settings/user/${UserStore.getUserID()}`);
	},

	// Hitting a route with variable params will also update the internal
	// router store.
	*'/settings/user/:user' (next) {
		// Kick off an ajax request. We don't neex to yield because our 
		// view can handle rendering with some empty store values
		ActionCreator.getUserSettings(this.params.user);
	}
});

// And then we expose a react class for people to render anywhere through
// Router.Component or something. Here's what Router.Component would =
React.createClass({
	mixins: [Router.mixin],

	getStateFromStores () {
		let ReactClass = Router.getReactClass();

		// Any named route params become {param: value} props
		let props = Router.getReactProps(); 

		return {
			reactComponent: <ReactClass {...props}></ReactClass>
		}
	},
	render () {
		return {this.state.reactComponent}
	}
});
```

**Comment by jhorwit2** [comment]
Could we instead of requiring the `*` in the router abstract that inside the `Router` object itself?

**Comment by mako-taco** [comment]
I don't know of a way to turn a normal fn into a generator fn.  I'm not sure babel will even let me build a normal fn with a `yield` in it.

**Comment by jhorwit2** [comment]
@santihbc - Any thoughts on this working example?

The thought for this design came from koa/express. The middleware / routes are generators, so you can control async flow. It's a pure flux design and uses our OO store under the hood. 

The Router object itself has a mixin you can use in any component to get current values related to the router like the path, query params, path params, etc. 

```javascript
Router
	.use(function *authentication(next) {
		if (!checkAuth()) {
			this.navigateTo('default');
			return;
		}
		yield *next;
	})
	.all('*', function *handler(next) {
		// Gets called before any route that matches `*`
		yield *next;
	})
	/**
	 * yay default routes
	 */
	.route('/', 'default', function *handler(next) {
		this.setReactElement(SomeElement, {defaultProps});
		yield *next;
	}, {
		default: true,
		title: 'FluxThis'
	})
	/**
	 * Navigate to any route matching /foo/somevalue
	 * do some foo stuff
	 */
	.route('/foo/:bar', 'setupFoobar', function *handler(next) {
		const pathParams = this.getPathParams();
		this.setReactElement(FooBar, {propValue: pathParams.get('bar')});
		yield *next;
	}, {
		title: 'FluxThis | Foo'
	})
	/**
	 * Lets execute this guy after all the other middleware / routes are done
	 */
	.use(function *done(next) {
		// Possibly do some stuff after routes are done??
		yield *next;
	})
	.start();
```

The way you use the router is with a React component that uses the RouterStore.mixin to listen for route changes. 

```javascript
React.createClass({
	displayName: 'MainComponent',
	mixins: [RouterStore.mixin],
	getStateFromStores() {
		return {
			reactElement: RouterStore.getReactElement(),
			reactElementProps: RouterStore.getReactElementProps()
			// you can also use any other getters from the store
			// like getPath, getQueryParams, getPathParams
		};
	},
	render() {
		let {ReactComponent, props} = this.state;
		
		return (
			<HeaderComponent />
				
			<ReactElement {...props} />
		
			<FooterComponent />
		);
	}
});
```

One thing this approach is awesome at is you can plug and play with middleware. You can also start to structure your routes just like you do with express in files, then add them all at once (not shown above). Modular ftw.

**Comment by santihbc** [comment]
I think this could really work in general and for my specific use case.

What I am trying to accomplish with the Flux architecture is a way to make actions playable (for analytics reasons). By this I mean, if I store all the actions that go through the dispatcher in an array and with the actions timestamped, I want to be able to take that array, calculate the time difference between all actions and then know what a user of my app has done simply by firing up the app on my computer and queuing the array of actions through my dispatcher with the appropriate timings.

The challenge with this is always the initial route, the entry point of a user to my app won't always be "/" of course. That is why I am looking for a router that fires an initial action that I can save and pipe into my development machine dispatcher to properly mimic the entry point my user accessed my up through. This also means, the router has to be rather passive, silently updating the URL as I navigate through the app so I can see myself using the "this.rewrite()" method a lot.

From what I can see, this router fits my (selfish) use case and I really enjoy the middleware functionality. I really don't see at this point what the router is missing but I would have to port one of our internal tools to FluxThis, which I will very soon :).

**Comment by jhorwit2** [comment]
Newer / nicer and more modular approach to routes.

Router.js
```javascript

const Router = require('fluxthis/src/router');

const userRoutes = require('./userRoutes');
const authMiddleware = require('./authMiddleware');

Router
    .register(authMiddleware)
    .register(userRoutes)
    .start();
```

userRoutes.js
```
export default function userRoutes(router) {
    router.route('/', 'default', function *handler(next) {
        this.setReactElement(el);
	    yield *next;
    }, {
	default: true
    });

    router.route('/user/:id', 'user', function *userHandler(next) {
        // do some stuff
    });
}
```

authMiddleware.js
```javascript

export default function authMiddleware(router) {
    router.all('/user*', function *authMiddleware(next) {
        if (failsAuth()) {
           this.navigateTo('default');
           return; 
       }
       yield *next;
    });
}
```

**Comment by santihbc** [comment]
This looks great. What are the following steps to get this into master?

**Comment by santihbc** [comment]
Any news on this @jhorwit2 ?

**Comment by jhorwit2** [comment]
Certain parts are ready, but still have some work left on history & nailing down details. I'm hoping by the end of this week it will be master worthy. :+1:

**Comment by jhorwit2** [comment]
@santihbc - the router seems in a good spot right now. I just need to work on tests & documentation.

**Comment by jhorwit2** [comment]
Been working on it over here: https://github.com/jhorwit2/fluxthis-router

**Comment by jhorwit2** [comment]
PR #76 is now open for the router & link to current docs for it http://dev.fluxthis.io/#/docs/router

**Comment by jhorwit2** [comment]
The router has been landed and added to the documentation & published; however, it is as experimental feature for the time being until it has been used and tested more.
