### ISSUE TITLE
How does API Action Creators work?

### ISSUE THREAD

**Issue by daannijkamp** [addthis/fluxthis#59]
Maybe i'm missing something, but how does a API Action Creator work?
I've a flux app running on, let say http://www.fluxapp.com/index.html
My flux app makes contact with an api, running on http://www.api.com/customers/...

How can i let my flux app know what the base url (http://www.api.com/) of my api is ?
Is this possible at all?

**Comment by mako-taco** [comment]
This isn't possible with the current APIActionCreator, as it does not have CORS or JSONP support. It's something we might add in the future, but for now, you can use the basic `ActionCreator` and make your requests inside of `createPayload`.
