### ISSUE TITLE
Error with APIActionsCreator

### ISSUE THREAD

**Issue by angelocala94** [addthis/fluxthis#61]
My console shows an error:
Uncaught Error: Invariant Violation: The method `createRequest` could not be created on `[APIActionCreator AuthAPIActionCreator]`; `route` must be a `string`, like "/example/:example"

but my code seems to be correct, route is a string!
```javascript
export default new APIActionCreator({
    displayName: 'AuthAPIActionCreator',
    actionSource: ACTION_SOURCES.AUTH_MODULE,
    signIn: {
        route: '/api/v1/test',
        method: 'POST',
        success: ACTION_TYPES.SIGN_IN_SUCCESS,
    },
    createRequest(email,password){
      return{
        query:{
          email:email,
          password:password
        }
      }
    }
});
```
where i'm wrong?

**Comment by mako-taco** [comment]
`createRequest` should be part of the definition of the api method (`signIn` in this case)
```js
export default new APIActionCreator({
    displayName: 'AuthAPIActionCreator',
    actionSource: ACTION_SOURCES.AUTH_MODULE,
    signIn: {
        route: '/api/v1/test',
        method: 'POST',
        success: ACTION_TYPES.SIGN_IN_SUCCESS,
        createRequest(email,password){
          return{
            query:{
              email:email,
              password:password
            }
          }
        }
    }
});
```

**Comment by angelocala94** [comment]
So, the docs of APIActionCreator is wrong!
https://fluxthis.io/#/docs/api-action-creators

Thanks for your help.

**Comment by jhorwit2** [comment]
@angelocala94 Good catch, I'm fixing that now. Will be pushed shortly

**Comment by angelocala94** [comment]
Thanks @jhorwit2

**Comment by jhorwit2** [comment]
It's up on http://fluxthis.io now!

@angelocala94 Just an fyi, we have all our docs stored in markdown over at https://github.com/addthis/fluxthis.io. Feel free to submit any PRs if you want :)
