### ISSUE TITLE
Pass Response on success - APIActionCreator

### ISSUE THREAD

**Issue by angelocala94** [addthis/fluxthis#62]
I have this APIActionCreator. I want to pass the response of my api server at the SIGN_IN_SUCCESS action. How to do it? With a normal Action Creator this can be done with the payloadType.
```javascript
export default new APIActionCreator({
    displayName: 'AuthAPIActionCreator',
    actionSource: ACTION_SOURCES.AUTH_MODULE,
    signIn: {
        route: options.apiPrefix+'/signin',
        method: 'GET',
        success: ACTION_TYPES.SIGN_IN_SUCCESS,
        payloadType: ActionCreator.PayloadTypes.string.isRequired
        createRequest(email,password){
          return{
            query:{
              email:email,
              password:password
            }
          }
        }
    }
});
```

**Comment by jhorwit2** [comment]
If I'm understanding your question correctly, this is done by default. 

If your response is successful, then the action that's dispatched has both the original request and the response from the server. 

here is an example of one from our code

```       
         /**
         *
         * @param {object} params
         * @param {object} params.response
         * @param {object} params.request
         */
        doStuff(params) {
            let data = params.response; // json data returned by server
        }
```

This handler is the method that we registered in our store. So, in your example it would be the

```
this.bindActions(
    ACTION_TYPES.SIGN_IN_SUCCESS: this.doStuff
);
```

**Comment by jhorwit2** [comment]
Just to be clear:

The actions registered for failed & success both get passed the response & request. 

If you register a pending action in the api action creator then you only get the request as the payload.

**Comment by angelocala94** [comment]
Yes, i have seen it now from your source code. 
```javascript
// Setup action for success/failure
action = {
	source: actionSource,
	type: success ? successActionType : failureActionType,
	payload: {
		request,
		response
	}
};
```
Response and Request are passed in the action, but i can't find it in docs.

**Comment by jhorwit2** [comment]
Sorry about that, I'm going to look into making those docs more clear and also make an example that you can run / tinker / look at!

Just another side note that should be documented, we don't have support for 

` payloadType: ActionCreator.PayloadTypes.string.isRequired`

in the api action creator. This could be something we add support for. The use case I'm thinking in my head is that we validate the values passed to createRequest. I'll talk with @mako-taco about that.

**Comment by jhorwit2** [comment]
Is it cool to close this issue?

**Comment by angelocala94** [comment]
Yes, i think that the documentation is the most important thing about a project. If it's clear and complete, makes the whole project better. Thanks!

**Comment by jhorwit2** [comment]
I agree, which is why I quickly wrote up a little snippet to explain pending, failure and success. :)

https://fluxthis.io/#/docs/api-action-creators
