### ISSUE TITLE
Create an example application with an API Action Creator 

### ISSUE THREAD

**Issue by jhorwit2** [addthis/fluxthis#63]
We need to setup some example application that ideally uses express or some other simple server implementation to demonstrate our api action creator.

**Comment by focusj** [comment]
Yeah, this would be very helpful for new comers. I also tried to create some API Actions, all the things worked very well, but there is a warning log: `The following actions have handlers in stores, but no ActionCreator has registered an action for them...` . Below is my code: 
```js
export default new APIActionCreator({
    displayName: 'UserAPIActionCreator',
    actionSource: ACTION_SOURCES.API,
    getJson: {
        route: api,
        method: 'GET',
        pending: ACTION_TYPES.RECEIVE_PENDING,
        handleSuccess(request, response) {
      		actionType: ACTION_TYPES.RECEIVE_SUCCESS
      		payloadType: ActionCreator.PayloadTypes.object.isRequired
        }
    }
});

///Store Code
		this.bindActions(
			ACTION_TYPES.RECEIVE_SUCCESS, this.jsonLoaded,
			ACTION_TYPES.RECEIVE_PENDING, this.setIsPending
		);
```
The log indicates that `RECEIVE_PENDING` and `RECEIVE_SUCCESS` were not registered on an ActionCreator. I debug the code, in `debug.es6.js` i can not find `UserAPIActionCreator` in registeredActions.I don't know why? Did i do something wrong? Should I care about this warning?

**Comment by mako-taco** [comment]
9 times out of 10, `handleSuccess` is not required. What you want to do is this:
```js
export default new APIActionCreator({
    displayName: 'UserAPIActionCreator',
    actionSource: ACTION_SOURCES.API,
    getJson: {
        route: api,
        method: 'GET',
        pending: ACTION_TYPES.RECEIVE_PENDING,
    }
});
```

**Comment by focusj** [comment]
@mako-taco this is not the root cause of the warning log. Just now i take some time to do a fully research, the root cause maybe is: In `APIActionCreator.createPublicMethod ` this method doesn't invoke `debug.registerAction`, because i found `debug.registerAction` invoked in `ActionCreator.createPublicMethod`. So this is why every thing is good, just a warning msg. 
By the way, @mako-taco what you said is very helpful for how to use ApiActionCreator correctly.

**Comment by mako-taco** [comment]
Oh, _that_ warning! Yes... I have been meaning to get rid of it entirely.  Ended up not being particularly helpful

**Comment by jhorwit2** [comment]
I'm closing this for the time being and marking it as future to revisit.
