### ISSUE TITLE
Example repo no longer works

### ISSUE THREAD

**Issue by tjwudi** [addthis/fluxthis#75]
[mako-taco/react-fluxthis-webpack-mocha-gulp](https://github.com/mako-taco/react-fluxthis-webpack-mocha-gulp) is using fluxthis@1.3.x which is not compatible with the latest stable version.

**Comment by jhorwit2** [comment]
The repository should still work, it just needs to be updated. Feel free to submit a PR to his repository or we can take a look at it also. Im closing this as this ticket shouldnt be in the main repo, but perhaps the fluxthis.io one.
