### ISSUE TITLE
Question: Writing Specs for ApiActionCreators

### ISSUE THREAD

**Issue by AaronBetterOfficeApps** [addthis/fluxthis#84]
We have been struggling through various approaches at testing a APIActionCreator. I have experimented with mocking out the AJAX requests using nock, as the request is async we never seem to be able to asset our expectation from a response. We also haven't been able to get our tests to a point where the success and failure callback functions are executed.

Could you provide some information as to the best strategy for testing ApiActionCreators in your experience?

We are using mocha on the command line if that is of any help.

**Comment by jhorwit2** [comment]
Hey,

I'm curious about the way you are attempting to test the API Action Creator. Would you mind pasting one of your tests (or a few tests).

**Comment by AaronBetterOfficeApps** [comment]
This is our current very nasty attempt. We have tried a few different have tried to solved this from a few other angles, but without much luck. We have just started to move from facebook's flux.js to fluxthis.js Previously with flux.js the actions were wrapped in promises, something we want to move away from, but it did make it a little easier to test as we could place the expectation in the then function.

```javascript
import LoginAPIActionCreator from 'src/login_app/actions/login_api_action_creator.es6'
import LoginStore from 'src/login_app/stores/login_store.es6'

let { API_URL } = process.env;

domSpec('LoginAPIActionCreator', (done)=>{

  describe('login',()=>{
    it('gets an auth token with valid credentials',()=>{

      sandbox.stub()

      nock(API_URL)
        .post('/login', { username: 'Matt', password: 'Gradayum' })
        .reply(200,
          {
            auth_token: '12345',
            success: 'true'
          }
        )


      LoginAPIActionCreator.login({username:'Matt', password: 'Gradayum'});
      
      setTimeout(() => {
        expect(window.location.href).to.eq('/');
        done();
      }, 100);

      clock.tick(200);
    });
  });
});
```

**Comment by jhorwit2** [comment]
Thanks for providing that so quickly. 

The first question I have is if you are running this on a single page app? Because if you are testing this in mocha & phantom headless then your test won't work correctly if the page hard refreshes.

Quick note about mocha, you should always use `done` passed to `it` for each test, so mocha knows to wait the predefined timeout time for each `it` call. 

```
import LoginAPIActionCreator from 'src/login_app/actions/login_api_action_creator.es6'
import LoginStore from 'src/login_app/stores/login_store.es6'

let { API_URL } = process.env;

domSpec('LoginAPIActionCreator', ()=>{

  describe('login',()=>{
    it('gets an auth token with valid credentials', (done)=>{

      sandbox.stub()

      nock(API_URL)
        .post('/login', { username: 'Matt', password: 'Gradayum' })
        .reply(200, () -> {done();})

      LoginAPIActionCreator.login({username:'Matt', password: 'Gradayum'});

      clock.tick(200);
    });
  });
});```

I have a limited understanding of nock; however, that should work. Basically you are expecting that the endpoint will get called, that means if the reply function gets called the action creator did its job.

**Comment by jhorwit2** [comment]
Another random note about your test, it's not clear what you are actually trying to test. `gets an auth token with valid credentials` is what you are returning from the mock, not what you are testing. A better name would be `should call /login when the action creator .login() method gets called` or something.

**Comment by jhorwit2** [comment]
I'm closing this as it's not an issue. I'll keep responding even if the ticket is closed.

**Comment by mako-taco** [comment]
If you are trying to test the _functionality_ of an `APIActionCreator`, I'd recommend doing it by using nock and creating a `Store` which is bound to the actions you are trying to test. @jhorwit2's method is good for asserting that a specific URL is getting requested, though.

**Comment by AaronBetterOfficeApps** [comment]
Your correct it's not the clearest test, we have only just made the decision to move to fluxthis. This was the first test we had attempted to write for a APIActionCreator. The final specs would have been cleaned up, this would mostly just and experiment to get started.

We are using it as part of a SPA, but we have architecture that splits the sign on into it's own front-end app, that then puts the auth token into local storage and redirects to another url that will load another react/flux app. So what we will need to test is that you are redirected to the correct app

**Comment by AaronBetterOfficeApps** [comment]
We understand that this is a strange use case, but we would still need to mock out the ajax request for a standard api action creator test, where we would assert the results against the store.

While trying to get the handleSuccess callbacks to output something we were unable to receive output at all.

We ended up going with sinon's mock xhr (nock doesn't seem to support ajax), and debugging this led me to the promise being initialised in [implore.js here](https://github.com/addthis/fluxthis/blob/master/lib/implore.es6.js#L43) never calling the callback.
I understand that this could be due to some random dependency overriding your version of es6 Promise, but if you could provide a small example as to how you guys mock out xhr requests that would be fantastic.

Thanks
Aaron & Matt

**Comment by mako-taco** [comment]
We actually _do not_ mock XHR requests. We unit test our stores and servers, and assume the glue between the two works (as it is entirely comprised of FluxThis, which has its own unit tests, and the browser).

We have a unit test in FluxThis specifically for ensuring that `handleSuccess` gets called:

```js
 it('should call handleSuccess on a successful request', function (done) {
        var aac = new APIActionCreator({
			displayName: 'api2',
            doThing: {
                route: '/mirror',
                method: 'POST',
                pending: 'TEST_' + Math.random(),
                handleSuccess: function () {
                    done();
                },
                handleFailure: function (req, res) {
                    done(req.error || res.error || new Error('Request failed'));
                }
            }
        });

        aac.doThing();
    });
```

The resolving promise does not directly call `handleSuccess`, though. Once a request has finished, the response is checked via a provided `successTest`, or the default one, built in to `APIActionCreator`:

```js
static defaultSuccessTest(response) {
  return response &&
    response.status &&
    response.status >= 200 &&
    response.status < 300;
}
```

You can see the relevant code in `APIActionCreator` here: https://github.com/addthis/fluxthis/blob/master/src/APIActionCreator.es6.js#L158
