### ISSUE TITLE
Router: Invariant Violation: You can only start the router once

### ISSUE THREAD

**Issue by AaronBetterOfficeApps** [addthis/fluxthis#85]
Having a little trouble getting the router to work [Caused by this line](https://github.com/addthis/fluxthis/blob/master/src/Router.es6.js#L61) as soon as we comment this out we are able to get things moving forward a little. We placed a debugger on this line a check that started is set to false, but once we continue execution it blows up. After commenting it out there are other errors we get with `setReactElement` not available on this inside the routes. We are working on pr for these errors but you may already have something in the pipeline.

Output from the debugger in the route handler: (notes in route.js)

![screen shot 2015-06-24 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/12239036/8338995/4aa02940-1a69-11e5-9eff-570b77551bab.png)

main.coffee
```coffeescript
Layout = require('src/layout/components/layout_foo')
routes = require('./routes')
React.render(<Layout />, document.getElementById('lendesk-app'));

Router
  .defaultRoute('/')
  .register(routes)
  .start(); # make sure to call start
```

layout.js (our controller view)
```javascript
import React from 'react';
import { RouterStore } from 'fluxthis';

export default React.createClass({
  displayName: 'Layout',
  mixins: [RouterStore.mixin], // Should use the immutable pure render mixin here :)
  getStateFromStores() {
    return {
      reactElement: RouterStore.getReactElement(),
      reactElementProps: RouterStore.getReactElementProps(),
      queryParams: RouterStore.getQueryParams(),
      pathParams: RouterStore.getPathParams(),
      path: RouterStore.getPath()
    };
  },
  render() {
    const ReactComponent = this.state.reactElement;
    if (!ReactComponent) {
      return null;
    }


    return (
      <div>
        <ReactComponent {...this.state.reactElementProps} />
      </div>
    );
  }
});
```

routes.js
```javascript
let ReleaseNotes = require('src/release_notes/components/release_notes');
require("babel/polyfill")

export default (router) => {
  router.route('/', 'root', function *defaultHander(next) {
    this.redirectTo('/release_notes');
  });

  router.route('/release_notes', 'release_notes', function *(next){
    //debugger When running this debugger this does not have a setReactElement method
    this.setReactElement(ReleaseNotes);
    yield *next // default id as prop
  });
};
```

Thanks,
Aaron and Matt

**Comment by jhorwit2** [comment]
Good catch. Sorry about the delay getting back. I'm fixing now.

**Comment by jhorwit2** [comment]
Just fyi, this feature is experimental as noted in the docs. We plan to make it a full fledged feature once we are able to integrate it into addthis.com & test it fully.

**Comment by jhorwit2** [comment]
v2.2.2 has been published.

**Comment by AaronBetterOfficeApps** [comment]
Thank you very much for fixing this so quickly.
