### ISSUE TITLE
implore.js / xhr.withCredentials

### ISSUE THREAD

**Issue by re5et** [addthis/fluxthis#90]
I have a static fluxthis app sitting at a sub domain and an api at another subdomain and I would like to have xhr.withCredentials set so cookies can be included, is there a reason that implore.js does not support this as an option?  Can I open a pull request to add it?

**Comment by jhorwit2** [comment]
Yup, feel free to PR. It's just not something we have come to need yet, but not a reason we won't gladly accept a PR!

**Comment by re5et** [comment]
Add https://github.com/addthis/fluxthis/pull/92

Not terribly elegant, but it solves my problem.  Not sure how to implement it in a neater fashion.

**Comment by jhorwit2** [comment]
Please update the PR if you wish to land this feature.

Thanks!
