### ISSUE TITLE
[QUESTION] How to use store mixin with es6 in react?

### ISSUE THREAD

**Issue by max107** [addthis/fluxthis#95]

**Comment by jhorwit2** [comment]
https://fluxthis.io/#/docs/controller-views

Does this answer your question?

**Comment by max107** [comment]
No, sorry. I read all documentation and i am beginner in es6. Example react component:

```js
class MySuperComponent extends React.Component {
// mixins? how?
}
```

Sorry for my bad english.

**Comment by jhorwit2** [comment]
Oh sorry, mixins don't work in es6 react classes. That's a React thing. You should just use `React.createClass` for the time being.

**Comment by jhorwit2** [comment]
You could try something like this https://github.com/brigand/react-mixin, but not 100% sure it works for this. We don't use ES6 classes so this hasn't come up.

**Comment by max107** [comment]
Oh, ok. i will try to use https://github.com/brigand/react-mixin.
Thanks.
