### ISSUE TITLE
question: ApiActionCreator-esk class for other remote protocols

### ISSUE THREAD

**Issue by engenb** [addthis/fluxthis#97]
Hey all,

Pulling FluxThis into my project because it's awesome, hands down. It's saving me so much time, so thanks for that!

In addition to hitting a restful API from my web client, I'm also publishing messages to a cloud messaging solution, PubNub.

What would be awesome, is if there was a nice place to plug their js client (or any other remote protocol client) into some kind of ActionCreator that manages the remote message flow just like ApiActionCreator does. However, instead of send(...) building and sending the XmlHttpRequest, send could be a required function supplied in the options hash. successTest could be required in this case as well to determine response validity.

So, you'd have ActionCreator for generic internal actions, ApiActionCreator that covers (probably most) server communication, and a RemoteActionCreator to support other remote client frameworks.

I totally get that your "super opinionated" framework may not want to include a hook to "send stuff however you want" so I'd understand hesitation, but I'm hoping you could see the value-add here for scenarios like mine.

In the meantime, I've simply extended ActionCreator to do what I've described above and I'd be happy to submit a pull request! Or, is there a more appropriate way to do this within the bounds of the framework as is? I've seen some code examples of making remote requests in ActionCreator.createPayload, which seems a little odd/misleading to me. But if that's the preferred approach, let me know!

Thanks!

**Comment by jhorwit2** [comment]
I'm thinking you best bet is to use a traditional flux approach to server communication.

We outlined how you can do that here with our framework: https://fluxthis.io/#/docs/action-creators
The first example shows you how you can accomplish custom communication mediums via the ActionCreator. 

Does this work for you?

**Comment by mako-taco** [comment]
The name 'createPayload' was conceived before it was apparent that we needed to provide some mechanism for people to put more events on the event loop at the same time that an action was created.  Definitely does not make any sense, but it's a perfectly OK way to do things.

**Comment by engenb** [comment]
Makes sense.  My ```RemoteActionCreator``` has been working pretty well for my team so far.  Only downside is the FluxThis debug object isn't exposed outside the framework, so the instance I'm getting is different.  This causes warnings as stores and action creators that ```require('fluxthis').ActionCreator```, for example, are registering with a different debug object.  Not a big deal, but reduces the value that provides.

Didn't submit this as a formal pull request as it sounds like you'd prefer to stick with the current ActionCreator for performing this sort of task, but I thought I'd post the code anyway in case it inspires some ideas for future enhancements to the framework!  Thanks!

```
'use strict';

const dispatcher = require('fluxthis').dispatcher;
const invariant = require('invariant');
const debug = require('fluxthis/src/debug.es6');
const ActionCreator = require('fluxthis/src/ActionCreator.es6');

export default class RemoteActionCreator extends ActionCreator {

	constructor(options) {
		super(options, { successTest: 1 });
	}

	createPublicMethod(name, options) {
		const {payload: payloadType} = options;
		const {createPayload, handleSuccess, handleFailure} = options;
		const {send: sendPayload,
			success: successActionType,
			failure: failureActionType,
			pending: pendingActionType} = options;

		// successTest can come from the top level object
		// or each function can use their own successTest.
		const successTest = options.successTest || this.successTest;

		const actionSource = this.actionSource || this.displayName;

		invariant(
			successTest instanceof Function,
			'The method `%s` could not be created on `%s`; ' +
			'`successTest` must be a `Function`',
			name,
			this
		);

		invariant(
			sendPayload instanceof Function,
			'The method `%s` could not be created on `%s`; ' +
			'`sendPayload` must be a `Function`',
			name,
			this
		);

		invariant(
			createPayload === undefined || createPayload instanceof Function,
			'The method `%s` could not be created on `%s`; ' +
			'If provided, `createPayload` must be a `Function`',
			name,
			this
			);

		invariant(
			handleSuccess === undefined || handleSuccess instanceof Function,
			'The method `%s` could not be created on `%s`; ' +
			'If provided, `handleSuccess` must be a `Function`',
			name,
			this
			);

		invariant(
			handleFailure === undefined || handleFailure instanceof Function,
			'The method `%s` could not be created on `%s`; ' +
			'If provided, `handleFailure` must be a `Function`',
			name,
			this
			);

		if (pendingActionType) {
			debug.registerAction(this, { type: pendingActionType, source: actionSource });
		}

		if (successActionType) {
			debug.registerAction(this, { type: successActionType, source: actionSource });
		}

		if (failureActionType) {
			debug.registerAction(this, { type: failureActionType, source: actionSource });
		}

		this[name] = (payload, ...args) => {
			if (createPayload) {
				payload = createPayload.apply(this, [payload, ...args]);
			}

			if(payloadType) {
				this.validatePayload(name, payload, payloadType);
			}

			debug.logActionCreator(this, name, payload, ...args);

			// If the user wants to dispatch a pending action
			// then we do that here.
			if (pendingActionType) {
				dispatcher.dispatch({
					source: actionSource,
					type: pendingActionType,
					payload: payload
				});
			}

			new Promise(handleResponse => sendPayload.call(this, payload, handleResponse))
				.then(result => {
					invariant(
						result instanceof Object && result.response && result.request,
						'The remote response could not be processed on `%s`; ' +
						'send must return an `Object`, like { request: {}, response: {} }',
						name,
						this
						);

					const request = result.request;
					const response = result.response;
					const success = successTest(response);

					// These methods allow the user to process
					// the request and modify it how they please
					// or dispatch more actions.
					if (success && handleSuccess) {
						handleSuccess.call(this, request, response);
					} else if (handleFailure) {
						handleFailure.call(this, request, response);
					}

					dispatcher.dispatch({
						source: actionSource,
						type: success ? successActionType : failureActionType,
						payload: {
							request: request,
							response: response
						}
					});
				});
		};
	}

	toString() {
		return `[RemoteActionCreator ${this.displayName}]`;
	}
}
```

**Comment by mako-taco** [comment]
Thanks... this makes me want to break up `createPublicMethod` into things that are more overridable so we can get more code re-use when extending `ActionCreator`

**Comment by engenb** [comment]
that sounds great!  it'd be awesome, if something like ```sendRequest``` was defined for an ```ApiActionCreator``` instead of on the public method.  you could define how "this action creator sends remote requests".  maybe the default impl of that could be REST - similar to what's in ```ApiActionCreator``` today, but could be overridden.  that way, the framework still enforces best practices without leaving too much rope for implementors to hang themselves.
